M48
; DRILL file KiCad 10.0.0 date 2026-04-06T11:01:03
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-06T11:01:03-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.250
%
G90
G05
T1
X168.995Y-139.173
X174.775Y-139.173
T2
X145.169Y-78.16
X145.169Y-86.136
T3
X201.215Y-137.6
X201.215Y-143.6
M30
